# Generated by Django 3.1.5 on 2021-01-18 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitedBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookid', models.CharField(default='None', max_length=128, unique=True)),
                ('img_url', models.URLField(max_length=2048)),
                ('title', models.CharField(max_length=256)),
                ('date', models.CharField(max_length=128)),
                ('rating', models.IntegerField(null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_viewed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
