# Generated by Django 3.1.5 on 2021-01-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitedbooks',
            name='bookid',
            field=models.CharField(default='None', max_length=128),
        ),
    ]
